spring:
  datasource:
    url: jdbc:mysql://192.168.1.175:3306/wentu-cloud?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://47.107.62.218:3306/aljs-cloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    #username: root
    #spassword: derivative_#@!
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    validationQuery: select 'x'
  rabbitmq:
    ####连接地址
    host: 192.168.1.195
    ####端口号
    port: 5672
    ####账号
    username: admin
    ####密码
    password: admin
    ### 地址
    virtual-host: /
    ###开启消息确认机制 confirms
    publisher-returns: true
    publisher-confirm-type: true
    listener:
      simple:
        #acknowledge-mode: manual #手动确认
        retry:
          enabled: true # 开启消费者进行重试
          max-attempts: 5 # 最大重试次数
          initial-interval: 3000 # 重试时间间隔

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 5 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
    timeout: 8000ms # 连接超时时间（毫秒）

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

